# Esercizio 1

In [2]:
import numpy as np

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [139]:
a = np.array([1.2, 5.4, 6, 1.59])
b = np.array([5.2, 1.2, 1.5, 2])

print(np.sqrt(a))
print(np.exp(a / 2))
print(a + b)
print(a * b)

'''
ue = np.arange(0, 30, 0.5)
print(ue)

vue = np.linspace(1, 2, 100)
print(vue)
'''
vu = np.array([np.linspace(10, 20, 6), np.linspace(20, 10, 6)])
print(vu)
print("Prodotto scalare = ", np.dot(a, b))

cat = np.vstack((a, b))
print(cat)

y = cat * b
print(y)

diag = np.diag(a)
print(diag)

[1.09544512 2.32379001 2.44948974 1.26095202]
[ 1.8221188  14.87973172 20.08553692  2.214441  ]
[6.4  6.6  7.5  3.59]
[6.24 6.48 9.   3.18]
[[10. 12. 14. 16. 18. 20.]
 [20. 18. 16. 14. 12. 10.]]
Prodotto scalare =  24.9
[[1.2  5.4  6.   1.59]
 [5.2  1.2  1.5  2.  ]]
[[ 6.24  6.48  9.    3.18]
 [27.04  1.44  2.25  4.  ]]
[[1.2  0.   0.   0.  ]
 [0.   5.4  0.   0.  ]
 [0.   0.   6.   0.  ]
 [0.   0.   0.   1.59]]


# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [24]:
a = np.full((3, 4), [2,2,2,3])
print(a)

b = np.diag(np.repeat([2], 3))
B = np.concatenate((b, np.full((3, 10), range(1, 11))), axis=1)
print(B)

C = np.diag([2, 2, 2, 2, 2]) + np.diag([-1, -1, -1, -1], k=-1) + np.diag([-1, -1, -1, -1], k=1)
print(C)

x = np.full((2, 4), [2,2,2,3])
y = np.zeros((2, 4), dtype=int)
z = np.concatenate((np.zeros((2, 2), dtype=int), np.diag([2, 2])), axis=1)
D = np.vstack((x, y, z))
print(D)

[[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
[[ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]]
[[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
[[2 2 2 3]
 [2 2 2 3]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 2 0]
 [0 0 0 2]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [26]:
i = input("Please enter some input: ")
c = np.arange(1, 2*int(i), 2)
print(np.sum(c))

4


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

In [65]:
def fibonacci_iter(n) :
    i = 0
    c = 1
    pre = 0
    res = 1
    while i < n - 1 :
        res = pre + c
        i += 1
        pre = c
        c = res
    return res
print(fibonacci_iter(3))

def fibonacci_rec(n) :
    if (n == 0) :
        return 0
    if (n == 1) :
        return 1
    return fibonacci_rec(n-1) + fibonacci_rec(n-2)
print(fibonacci_rec(3))

import time as tm
start = tm.time_ns()
fibonacci_iter(24)
end = tm.time_ns()
print("Fibonacci iter: ", end - start, "ns")
start = tm.time_ns()
fibonacci_rec(24)
end = tm.time_ns()
print("Fibonacci rec: ", end - start, "ns")


2
2
Fibonacci iter:  55733 ns
Fibonacci rec:  29639870 ns
