# Esercizio 1

In [45]:
import numpy as np

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [139]:
a = np.array([1.2, 5.4, 6, 1.59])
b = np.array([5.2, 1.2, 1.5, 2])

print(np.sqrt(a))
print(np.exp(a / 2))
print(a + b)
print(a * b)

'''
ue = np.arange(0, 30, 0.5)
print(ue)

vue = np.linspace(1, 2, 100)
print(vue)
'''
vu = np.array([np.linspace(10, 20, 6), np.linspace(20, 10, 6)])
print(vu)
print("Prodotto scalare = ", np.dot(a, b))

cat = np.vstack((a, b))
print(cat)

y = cat * b
print(y)

diag = np.diag(a)
print(diag)

[1.09544512 2.32379001 2.44948974 1.26095202]
[ 1.8221188  14.87973172 20.08553692  2.214441  ]
[6.4  6.6  7.5  3.59]
[6.24 6.48 9.   3.18]
[[10. 12. 14. 16. 18. 20.]
 [20. 18. 16. 14. 12. 10.]]
Prodotto scalare =  24.9
[[1.2  5.4  6.   1.59]
 [5.2  1.2  1.5  2.  ]]
[[ 6.24  6.48  9.    3.18]
 [27.04  1.44  2.25  4.  ]]
[[1.2  0.   0.   0.  ]
 [0.   5.4  0.   0.  ]
 [0.   0.   6.   0.  ]
 [0.   0.   0.   1.59]]


# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [145]:
a = np.full((3, 4), [2,2,2,3])
print(a)

b = np.diag(np.repeat([2], 3))
for x in b:
    res = np.vstack((res, np.hstack((x, list(range(1, 11, 1))))))
print(res)
c = np.zeros((5, 5))
c = np.diag(np.repeat([2], len(c)))
print(c)

[[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
[[ 0  0  2  1  2  3  4  5  6  7  8  9 10]
 [ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]
 [ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]
 [ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]
 [ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]
 [ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]
 [ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]
 [ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]
 [ 2  0  0  1  2  3  4  5  6  7  8  9 10]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [122]:
n = 5
res = [x * 2 + 1 for x in range(0, n)]
print(np.sum(res))

25


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.