## Esercizi sui Numpy array  7 Marzo 2023


In [1]:
import numpy as np

- **0.** Costruisci un numpy array con 2000000 elementi equidistanti nell'intervallo [0,4] utilizzando il linspace e con il metodo che assegna i valori in un ciclo dopo aver definito il passo e confronta il tempo di esecuzione delle due modalità di costruzione.

In [10]:
arr = np.linspace(0, 4, 2000000)
print(arr)

[0.000000e+00 2.000001e-06 4.000002e-06 ... 3.999996e+00 3.999998e+00
 4.000000e+00]


- **1.**  Costruire un numpy array 1d, denominato  `c`, di valori equidistanti che variano tra 7 e 41 con step 2 e trasformarlo in un numpy array 2d, denominato `C1` , con shape(2,9) applicando il metodo `.reshape((m,n))` a c. 

  Si tratta di una copia o di una `vista dell'array originale` con una nuova shape, con dati condivisi con l'array originale?


In [11]:
c = np.arange(7, 42, 2)
c1 = np.reshape(c, (2, 9))
print(c, "\n",c1)

[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41] 
 [[ 7  9 11 13 15 17 19 21 23]
 [25 27 29 31 33 35 37 39 41]]


Importa il modulo numpy

 - **2.** Costruire un numpy array 1d, denominato $C$ di valori che variano tra 15 e 41 con step 2 e trasformarlo in un numpy array 2d con shape(7,2) usando il metodo .`resize(7,2)` che lavora in-place,  (cioè  modifica l'array esistente, senza creare una copia). Verificare la shape di C

In [15]:
c = np.arange(15, 42, 2)
c.resize(7, 2)
print(c.shape)

(7, 2)


- **3.** Costruire un numpy array 1d $c$ di valori che variano tra 15 e 41 con step 2 e trasformarlo in un numpy array 2d con shape(7,2) usando la funzione `reshape`. Verificare se la funzione  `reshape` restituisce una copia oppure una vista. 

In [21]:
c = np.arange(15, 42, 2)
c1 = c.reshape((7, 2))
print(c1.dtype, c.shape)

int64 (14,)


- **4.** Costruire un numpy array 1d $d$ di valori che variano tra 15 e 41 con step 2 e trasformarlo in un numpy array 2d con shape(7,2) usando la funzione `resize`. Verificare se la funzione  `resize` restituisce una copia oppure una vista. 

In [20]:
d = np.arange(15, 42, 2)
d.resize(7, 2)
print(d.dtype, d.shape)

int64 (7, 2)


- **5.** Dato il numpy array s formato da 100 valori equidistanti in  [0,4], considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne

In [35]:
s = np.linspace(0, 4, 100)
s1 = s.reshape((4, 100 // 4))
print(s1.shape)

(4, 25)


- **6.** Dato il numpy array s formato da 100 valori equidistanti in  [0,4], considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [36]:
s1 = s.reshape((100 // 4, 4))
print(s1.shape)

(25, 4)


 - **7.** Scrivere il numpy  array 2d [[10,11,12],[13,14,15],[16,17,18]] e trasformarlo in un numpy array 1d usando i metodi `.ravel()` e `.flatten()`. Verificare che flatten restituisce una copia mentre ravel restituisce una vista.

 - **8.** creare i due  numpy array 1d
f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] ed 
f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
"vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

- **9.**                Dati :
 - Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 - Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
"Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B



 - **10.** Creare un array 2D di shape (5,5), denominato B2, con valori tutti uguali a 15.
Creare una copia B3 di B2. Modificare l'elemento B3[0,0] assegnandogli il valore 150. 
Stampare il numpy array B2 ed il numpy array B3 e verificare che B2, dopo la modifica di B3, è rimasto inalterato

 - **11.** - Dato un numpy array 1D, di shape (10,) denominato `f`, costituito da 10 valori equidistanti nell'intervallo [0,1], aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

- **12.** Dati i seguenti numpy array
  - a= np.array([14,13,12,11])
  - b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe


- **13.** - Dati i seguenti numpy array
  - a= np.array([14,13,12,11])
  - b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per colonne

- **14.** Costruisci la matrice tridiagonale A di ordine 10, che ha elementi diagonali $A_{i,i}=10$, i=1,20, elementi nella codiagonale inferiore $A_{i-1,i}=-12$ i=2,..,20
elementi nella codiagonale superiore $A_{i,i+1}=-2$ i=1,..,19

 - **15** Costruire la matrice identità della stessa dimensione di A

- **16.** Selezionare dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2


- **17.** A1 è una vista di A, come trasformarla in copia?

- **18.** Costruisci due numpy array di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci in modalità element-wise le matrici
  C=A+B
  D=A-B
  E=A*B
  F=A\B

- **19.** Costruisci il prodotto scalare tra le  matrici A e B (righe per colonne)

- **20.** Somma gli elementi delle righe della matrice B

- **21.** Somma gli elementi delle colonne della matrice B

- **22.** Somma tutti gli elementi di B

- **23.** Calcolare il minimo degli elementi di B, tra le righe, tra le colonne, il minimo di tutta la matrice B

- **24** Calcola, memorizzando in un vettore, la somma degli elementi di ogni colonna di $ |B |$. Calcola successivamente il massimo di questo vettore.
$cmaxc= \max_{j=1,n} \sum_{i} |b_{ij}|$

- **25.** Calcola, memorizzando in un vettore, la somma degli elementi di ogni riga  di $ |B |$. Calcola successivamente il massimo di questo vettore.
$cmaxr= \max_{i=1,n} \sum_{j} |b_{ij}|$

- **26.** Effettua nella matrice B lo scambio tra la  riga 2 e  la riga 3

 - **27.** Calcola il valore massimo della colonna 0-esima della matrice B e l'indice di riga a cui appartiene

- **28.** Scrivi una funzione border(m,n) per creare un array 2D di shape(m,n) che abbia tutti valori zero, ad eccezione degli elementi attorno al bordo (ovvero la prima e l'ultima riga e la prima e l'ultima colonna), che deve avere un valore pari a uno. Prevedi un argomento di default che se impostato a True visualizza la matrice 

- **29.** Scrivi una funzione `visualizza(f,a,b)`che prende in input una lambda function, gli estremi dell'intervallo su cui è definita e la visualizzi in una finestra grafica

- **30.** Scrivi una funzione `visualizza2(f,a,b,f2,a2,b2)`che prende in input una lambda function f e gli estremi dell'intervallo su cui è definita, una lambda function f2 e gli estremi dell'intervallo su cui è definita, e l2 visualizzi sulla stessa finestra grafica

- 